// GENERATED by gitEr/dressChild.sh — edit the source in ~/DEV/fetch/rapper.
// Aliases are rapper's, rebased one level: ../rapper/gc becomes ./_rapper/gc.
import adapterStatic from "@sveltejs/adapter-static";
import { vitePreprocess } from "@sveltejs/vite-plugin-svelte";

/** @type {import('@sveltejs/kit').Config} */
export default {
	preprocess: vitePreprocess(),
	kit: {
		adapter: adapterStatic({ fallback: "index.html", strict: false }),
		alias: {
			// ORDER IS LOAD-BEARING: longest prefix FIRST, or a bare `$parent/*`
			// below swallows every `$parent/siblings/…` first.
			"$parent/siblings/getCache_OfflineMap/*": "./*",
			"$parent/siblings/getCache_OfflineMap": ".",
			// A sibling not named here is absent, so a new crossing fails to
			// resolve rather than resolving by luck.
			"$parent/siblings/getCache_OnlineMap/*": "./_siblings/getCache_OnlineMap/*",
			"$parent/siblings/getCache_OnlineMap": "./_siblings/getCache_OnlineMap",
			// $parent is the vendored rapper, which owns app.unique.css/app.html.
			"$parent/*": "./_rapper/*",
			$parent: "./_rapper",
			$rig: "./_rapper/rig",
			"$rig/*": "./_rapper/rig/*",
			$gc: "./_rapper/gc",
			"$gc/*": "./_rapper/gc/*",
			$rt: "./_rapper/rt",
			"$rt/*": "./_rapper/rt/*",
		},
		files: {
			routes: "routes",
			hooks: { universal: "hooks" },
			appTemplate: "_rapper/src/app.html",
			lib: "lib",
		},
	},
};
