// GENERATED by gitEr/dressChild.sh — edit the source in ~/DEV/fetch/rapper.
//
// Standalone head: this child runs on its own (`npm run dev`), with rapper
// vendored beside it in _rapper/. The aliases are rapper's, rebased one level:
// where a workspace checkout says ../rapper/gc, a dressed child says ./_rapper/gc.
import adapterStatic from "@sveltejs/adapter-static";
import { vitePreprocess } from "@sveltejs/vite-plugin-svelte";

/** @type {import('@sveltejs/kit').Config} */
export default {
	preprocess: vitePreprocess(),
	kit: {
		adapter: adapterStatic({ fallback: "index.html", strict: false }),
		alias: {
			// ORDER IS LOAD-BEARING: longest prefix FIRST. A bare `$parent/*` above
			// these swallows every `$parent/siblings/…` and rewrites it into a
			// _rapper/siblings/ path that does not exist — the same trap
			// vitest.config.ts documents for the workspace configs.
			//
			// This child, sitting beside rapper's copy as it does in a workspace.
			"$parent/siblings/getCache_OfflineMap/*": "./*",
			"$parent/siblings/getCache_OfflineMap": ".",
			// Siblings this child imports, vendored under _siblings/ by the same
			// script. A sibling it does NOT name is absent, so a new boundary
			// crossing still fails to resolve rather than resolving by luck.
			"$parent/siblings/getCache_OnlineMap/*": "./_siblings/getCache_OnlineMap/*",
			"$parent/siblings/getCache_OnlineMap": "./_siblings/getCache_OnlineMap",
			// $parent is the MOUNTING TIER, and here that is the vendored rapper —
			// it owns app.unique.css and app.html, which a child never has.
			"$parent/*": "./_rapper/*",
			$parent: "./_rapper",
			$rig: "./_rapper/rig",
			"$rig/*": "./_rapper/rig/*",
			$gc: "./_rapper/gc",
			"$gc/*": "./_rapper/gc/*",
			$rt: "./_rapper/rt",
			"$rt/*": "./_rapper/rt/*",
		},
		files: {
			routes: "routes",
			hooks: { universal: "hooks" },
			appTemplate: "_rapper/src/app.html",
			lib: "lib",
		},
	},
};
