// GENERATED by gitEr/dressChild.sh — edit the source in ~/DEV/fetch/rapper.
import { sveltekit } from "@sveltejs/kit/vite";
import { defineConfig } from "vite";

export default defineConfig({
	plugins: [sveltekit()],
	server: { fs: { allow: [".", "./_rapper", "./_siblings"] } },
});
